---
- name: restart sshd
  sudo: true 
  service: name=ssh state=restarted

- name: restart server
  sudo: true
  command: shutdown -r now 
  async: 0
  poll: 0
  ignore_errors: true
  notify: wait for server restart

- name: wait for server restart
  local_action: wait_for host={{ inventory_hostname }} port=22
                state=started
  sudo: false
